steps:
  # Build the image using Dockerfile
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}", "./timeseries_orm/"]

  # Push the built image to the container registry service
  - id: "push image to Container Registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}"]
  
  # Deploy Container Image to the Cloud Run 
  - id: "deploy image to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: 
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --allow-unauthenticated
      - --region=${_REGION}
      - --port=8080
      - --service-account=${_SERVICE_ACCOUNT_NAME}
      - --platform=managed

# Here are the substitution variables related to the services.
substitutions:
  _REGION: us-central1 # The region where the cloud services are located.
  _SERVICE_NAME: $$_SERVICE_NAME # The name of the App Cloud Run service (Any name you choose).
  _SERVICE_ACCOUNT_NAME: $$_SERVICE_ACCOUNT_NAME

# The structure of the built image
images:
  - gcr.io/${PROJECT_ID}/${_SERVICE_NAME}

